name: Hello World

# This workflow will run whenever code is pushed to the repository
on:
  push:
    branches:
      - main

jobs:
  hello-world-job:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Print "Hello World"
      - name: Hello World
        run: echo "Hello, World!"
